Imports System.Data

Module ModFunction
    Public Function SqlStr(param As String) As String
        Return "'" & param & "'"
    End Function

    Public Function BogusDatatable() As DataTable
        Dim table As New DataTable

        ' Add columns for Category and Subcategory
        table.Columns.Add("Category", GetType(String))
        table.Columns.Add("Subcategory", GetType(String))
        table.Columns.Add("Description", GetType(String))

        ' Add Address subcategories
        table.Rows.Add("Address", "ZipCode", "Get a zipcode.")
        table.Rows.Add("Address", "City", "Get a city name.")
        table.Rows.Add("Address", "StreetAddress", "Get a street address.")
        table.Rows.Add("Address", "CityPrefix", "Get a city prefix.")
        table.Rows.Add("Address", "CitySuffix", "Get a city suffix.")
        table.Rows.Add("Address", "StreetName", "Get a street name.")
        table.Rows.Add("Address", "BuildingNumber", "Get a building number.")
        table.Rows.Add("Address", "StreetSuffix", "Get a street suffix.")
        table.Rows.Add("Address", "SecondaryAddress", "Get a secondary address like 'Apt. 2' or 'Suite 321'.")
        table.Rows.Add("Address", "County", "Get a county.")
        table.Rows.Add("Address", "Country", "Get a country.")
        table.Rows.Add("Address", "FullAddress", "Get a full address like Street, City, Country.")
        table.Rows.Add("Address", "CountryCode", "Get a random ISO 3166-1 country code.")
        table.Rows.Add("Address", "State", "Get a random state state.")
        table.Rows.Add("Address", "StateAbbr", "Get a state abbreviation.")
        table.Rows.Add("Address", "Latitude", "Get a Latitude.")
        table.Rows.Add("Address", "Longitude", "Get a Longitude.")
        table.Rows.Add("Address", "Direction", "Generates a cardinal or ordinal direction. IE: Northwest, South, SW, E")
        table.Rows.Add("Address", "CardinalDirection", "Generates a cardinal direction. IE: North, South, E, W.")
        table.Rows.Add("Address", "OrdinalDirection", "Generates an ordinal direction. IE: Northwest, Southeast, SW, NE.")


        ' Add data
        table.Rows.Add("Commerce", "Department", "")
        table.Rows.Add("Commerce", "Price", "")
        table.Rows.Add("Commerce", "ProductName", "")
        table.Rows.Add("Commerce", "Categories", "")
        table.Rows.Add("Commerce", "Ean8", "")
        table.Rows.Add("Commerce", "Ean13", "")
        table.Rows.Add("Commerce", "Uuid", "")
        table.Rows.Add("Commerce", "Color", "")
        table.Rows.Add("Commerce", "Product", "")
        table.Rows.Add("Commerce", "ProductAdjective", "")
        table.Rows.Add("Commerce", "ProductMaterial", "")
        table.Rows.Add("Commerce", "ProductDescription", "")

        table.Rows.Add("Company", "CompanyName", "")
        table.Rows.Add("Company", "CompanySuffix", "")
        table.Rows.Add("Company", "CatchPhrase", "")
        table.Rows.Add("Company", "Bs", "")
        'table.Rows.Add("Company", "CatchPhraseAdjective", "")
        'table.Rows.Add("Company", "CatchPhraseDescriptor", "")
        'table.Rows.Add("Company", "CatchPhraseNoun", "")
        'table.Rows.Add("Company", "BsAdjective", "")
        'table.Rows.Add("Company", "BsBuzz", "")
        'table.Rows.Add("Company", "BsNoun", "")


        table.Rows.Add("Database", "Column", "")
        table.Rows.Add("Database", "Type", "")
        table.Rows.Add("Database", "Collation", "")
        table.Rows.Add("Database", "Engine", "")

        table.Rows.Add("Date", "Past", "")
        table.Rows.Add("Date", "PastOffset", "")
        table.Rows.Add("Date", "Future", "")
        table.Rows.Add("Date", "FutureOffset", "")
        table.Rows.Add("Date", "Recent", "")
        table.Rows.Add("Date", "RecentOffset", "")
        table.Rows.Add("Date", "Soon", "")
        table.Rows.Add("Date", "SoonOffset", "")
        table.Rows.Add("Date", "Between", "") 'Must have argument
        table.Rows.Add("Date", "BetweenOffset", "") 'Must have argument
        table.Rows.Add("Date", "Timespan", "")
        table.Rows.Add("Date", "Month", "")
        table.Rows.Add("Date", "Weekday", "")

        table.Rows.Add("Finance", "Account", "")
        table.Rows.Add("Finance", "AccountName", "")
        table.Rows.Add("Finance", "Amount", "")
        table.Rows.Add("Finance", "TransactionType", "")
        'table.Rows.Add("Finance", "Currency", "")
        table.Rows.Add("Finance", "CreditCardNumber", "")
        table.Rows.Add("Finance", "CreditCardCvv", "")
        table.Rows.Add("Finance", "BitcoinAddress", "")
        table.Rows.Add("Finance", "EthereumAddress", "")
        table.Rows.Add("Finance", "RoutingNumber", "")
        table.Rows.Add("Finance", "Iban", "")
        table.Rows.Add("Finance", "Bic", "")

        table.Rows.Add("Hacker", "Abbreviation", "")
        table.Rows.Add("Hacker", "Adjective", "")
        table.Rows.Add("Hacker", "Noun", "")
        table.Rows.Add("Hacker", "Verb", "")
        table.Rows.Add("Hacker", "IngVerb", "")
        table.Rows.Add("Hacker", "Phrase", "")

        table.Rows.Add("Internet", "Avatar", "")
        table.Rows.Add("Internet", "Email", "")
        table.Rows.Add("Internet", "ExampleEmail", "")
        table.Rows.Add("Internet", "UserName", "")
        table.Rows.Add("Internet", "UserNameUnicode", "")
        table.Rows.Add("Internet", "DomainName", "")
        table.Rows.Add("Internet", "DomainWord", "")
        table.Rows.Add("Internet", "DomainSuffix", "")
        table.Rows.Add("Internet", "Ip", "")
        table.Rows.Add("Internet", "Port", "")
        table.Rows.Add("Internet", "IpAddress", "")
        table.Rows.Add("Internet", "IpEndPoint", "")
        table.Rows.Add("Internet", "Ipv6", "")
        table.Rows.Add("Internet", "Ipv6Address", "")
        table.Rows.Add("Internet", "Ipv6EndPoint", "")
        table.Rows.Add("Internet", "UserAgent", "")
        table.Rows.Add("Internet", "Mac", "")
        table.Rows.Add("Internet", "Password", "")
        table.Rows.Add("Internet", "Color", "")
        table.Rows.Add("Internet", "Protocol", "")
        table.Rows.Add("Internet", "Url", "")
        table.Rows.Add("Internet", "UrlWithPath", "")
        table.Rows.Add("Internet", "UrlRootedPath", "")
        'table.Rows.Add("Internet", "Emoji", "")

        table.Rows.Add("Lorem", "Word", "")
        table.Rows.Add("Lorem", "Words", "")
        table.Rows.Add("Lorem", "Letter", "")
        table.Rows.Add("Lorem", "Sentence", "")
        table.Rows.Add("Lorem", "Sentences", "")
        table.Rows.Add("Lorem", "Paragraph", "")
        table.Rows.Add("Lorem", "Paragraphs", "")
        table.Rows.Add("Lorem", "Text", "")
        table.Rows.Add("Lorem", "Lines", "")
        table.Rows.Add("Lorem", "Slug", "")

        table.Rows.Add("Name", "FirstName", "")
        table.Rows.Add("Name", "LastName", "")
        table.Rows.Add("Name", "FullName", "")
        table.Rows.Add("Name", "Prefix", "")
        table.Rows.Add("Name", "Suffix", "")
        table.Rows.Add("Name", "FindName", "")
        table.Rows.Add("Name", "JobTitle", "")
        table.Rows.Add("Name", "JobDescriptor", "")
        table.Rows.Add("Name", "JobArea", "")
        table.Rows.Add("Name", "JobType", "")

        table.Rows.Add("Random", "Number", "")
        table.Rows.Add("Random", "Decimal", "")
        table.Rows.Add("Random", "Double", "")
        table.Rows.Add("Random", "Float", "")
        table.Rows.Add("Random", "Byte", "")
        table.Rows.Add("Random", "SByte", "")
        table.Rows.Add("Random", "Char", "")
        table.Rows.Add("Random", "String", "")
        table.Rows.Add("Random", "Hexadecimal", "")
        table.Rows.Add("Random", "Bool", "")
        table.Rows.Add("Random", "Uuid", "")
        table.Rows.Add("Random", "Guid", "")
        table.Rows.Add("Random", "AlphaNumeric", "")
        table.Rows.Add("Random", "Hash", "")
        table.Rows.Add("Random", "Replace", "")


        table.Rows.Add("System", "FileName", "")
        table.Rows.Add("System", "DirectoryPath", "")
        table.Rows.Add("System", "FilePath", "")
        table.Rows.Add("System", "CommonFileName", "")
        table.Rows.Add("System", "MimeType", "")
        table.Rows.Add("System", "CommonFileType", "")
        table.Rows.Add("System", "CommonFileExt", "")
        table.Rows.Add("System", "FileType", "")
        table.Rows.Add("System", "FileExt", "")
        table.Rows.Add("System", "Semver", "")
        table.Rows.Add("System", "Version", "")
        table.Rows.Add("System", "Exception", "")
        table.Rows.Add("System", "AndroidId", "")
        table.Rows.Add("System", "ApplePushToken", "")
        table.Rows.Add("System", "BlackberryPin", "")

        table.Rows.Add("Phone", "PhoneNumber", "")
        table.Rows.Add("Phone", "PhoneNumberFormat", "")

        table.Rows.Add("Rant", "Review", "")
        table.Rows.Add("Rant", "Reviews", "")

        table.Rows.Add("Vehicle", "Vin", "")
        table.Rows.Add("Vehicle", "Manufacturer", "")
        table.Rows.Add("Vehicle", "Model", "")
        table.Rows.Add("Vehicle", "Type", "")
        table.Rows.Add("Vehicle", "Fuel", "")
        BogusDatatable = table
    End Function
End Module
